# Generated by Django 3.2 on 2021-04-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElainRyhma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ryhma', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Elain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvm', models.DateTimeField(auto_now_add=True, null=True)),
                ('nimi', models.CharField(default='testi', max_length=50)),
                ('huomioon', models.TextField()),
                ('ryhma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.elainryhma')),
            ],
        ),
    ]
