# Generated by Django 3.2 on 2021-04-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElainRyhma',
            new_name='ElainKategoria',
        ),
    ]
